---
title: "Lab 5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(ggrepel)

library(lubridate)
library(plotly)
acc <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/accident.csv", stringsAsFactors = FALSE)
per <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/person.csv", stringsAsFactors = FALSE)
```

```{r}
str(acc)
str(per)
```


## 7
```{r}
# Variables I'll need: acc- County, Fatals

fatalsByCounty <- acc %>% select('FATALS','COUNTY') %>% group_by(COUNTY) %>%summarize(totalFat = sum(FATALS))
str(fatalsByCounty)
GLC <- readxl::read_xlsx('GLC.xlsx')
GLC$'County Code' <- as.numeric(GLC$'County Code')
GLC$`County Name` <- tolower(as.character(GLC$`County Name`))

updatedFatalities <- GLC %>% left_join(fatalsByCounty, by=c('County Code'='COUNTY'))
str(updatedFatalities)

county <-map_data("county")
summary(county)
str(county)
county$subregion <- as.character(county$subregion)
county %>% ggplot(aes(x=long, y=lat))+geom_polygon(aes(group=group),color='pink')



countycombine<- county %>% right_join(updatedFatalities, by = c('subregion'='County Name')) %>% select('subregion','long','lat','group','order','region', 'totalFat')
str(countycombine)

countycombine %>% ggplot(aes(x=long,y=lat))+geom_polygon(aes(group = group, fill = totalFat), color = "black")




```


## 8

```{r fig.width=11,fig.height=11}
#Seasons, winter = 1, spring = 2, summer = 3, fall = 4
acc <- 
  mutate(acc, SEASON = ifelse(MONTH %in% 7:11,'f',
        ifelse(MONTH %in% 3:5,'p', 
          ifelse(MONTH %in% 6:8,'s','w'))));

acc %>% filter(SEASON == 's' | SEASON == 'w') %>%
  ggplot(aes(x=SEASON, weight = FATALS)) + geom_bar()+xlab("Season")+ylab("fatalities")+ggtitle("Fatalities in Summer vs Winter In Each State")

str(GLC)
GLC$`State Code` <- as.numeric(GLC$`State Code`)
GLCUnique <- GLC %>% select('State Name','State Code') %>% distinct()
GLCUnique
withNames <- acc  %>% select(FATALS, SEASON, STATE) %>%left_join(GLCUnique, by=c(STATE = 'State Code'))
str(withNames)
str(acc)

withNames %>% filter(SEASON == 's' | SEASON == 'w') %>%
  ggplot(aes(x=SEASON, weight = FATALS)) + geom_bar() + facet_wrap( ~ `State Name`, scales = "free_y")+xlab("Season")+ylab("fatalities")+ggtitle("Fatalities in Summer vs Winter In Each State")

```

